### ISSUE TITLE
新建大屏失败，是什么原因？

### ISSUE THREAD

**Issue by chengsan2018** [food-billboard/create-chart#10]
![image](https://github.com/food-billboard/create-chart/assets/29742689/10d5b625-07d4-4bfd-b1d7-3c4a0903d63d)

**Comment by chengsan2018** [comment]
![image](https://github.com/food-billboard/create-chart/assets/29742689/af3e5c1f-ec0a-4e05-9c77-c39d85697887)

**Comment by food-billboard** [comment]
> ![image](https://private-user-images.githubusercontent.com/29742689/306820351-af3e5c1f-ec0a-4e05-9c77-c39d85697887.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NTg3MDcsIm5iZiI6MTcwODY1ODQwNywicGF0aCI6Ii8yOTc0MjY4OS8zMDY4MjAzNTEtYWYzZTVjMWYtZWMwYS00ZTA1LTljNzctYzM5ZDg1Njk3ODg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDAzMjAwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzODU2MGY4ZGZkZjI5Njk2Mzc2MGMyMjk5ZDJlYzI0YmFjOTI1NWFmMDM0NmIyMmI3YzRmMDVkNTU2YzU3NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wOjL_xQupT5bU8lX9ufxid3sW-FUWfaI_JbuApH2dnw)

老板改好了，清下缓存再试下吧

**Comment by chengsan2018** [comment]
大佬厉害!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月23日(星期五) 中午11:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [food-billboard/create-chart] 新建大屏失败，是什么原因？ (Issue #10)





  

  
老板改好了，清下缓存再试下吧

**Comment by chengsan2018** [comment]
![image](https://github.com/food-billboard/create-chart/assets/29742689/a523fef9-9c96-4019-ac7f-655f2c91aecd)
还是报错 我是使用的是我自己注册的帐号

**Comment by food-billboard** [comment]
> ![image](https://private-user-images.githubusercontent.com/29742689/307254769-a523fef9-9c96-4019-ac7f-655f2c91aecd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzcwNTMsIm5iZiI6MTcwODY3Njc1MywicGF0aCI6Ii8yOTc0MjY4OS8zMDcyNTQ3NjktYTUyM2ZlZjktOWM5Ni00MDE5LWFjN2YtNjU1ZjJjOTFhZWNkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA4MjU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMzA2ZDE3MDI1ZTcyY2VlNGQ4NTNhMzFjYTZmYmI5OTRmNzc5YmI1ZTBkYjIyMGI5ZTFhNDZiYWY5M2U3OTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n-EL0lnTWbUFjBV_-H2kQ9XRqUW5FgRv4Zv7HXI-_RQ) 还是报错 我是使用的是我自己注册的帐号

不会吧，你缓存清了吗，把接口参数发我看下

**Comment by chengsan2018** [comment]
大佬，能加一下我的微信cs1029927487吗？我微信发给你



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年2月23日(周五) 下午4:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [food-billboard/create-chart] 新建大屏失败，是什么原因？ (Issue #10)




  
 还是报错 我是使用的是我自己注册的帐号
  
不会吧，你缓存清了吗，把接口参数发我看下
