### ISSUE TITLE
请问作者项目是什么license？

### ISSUE THREAD

**Issue by gray0128** [food-billboard/create-chart#6]
请问作者项目是什么license？

**Comment by food-billboard** [comment]
> 请问作者项目是什么license？

这个不太懂是啥，单纯学习练手用的项目

**Comment by taoistwar** [comment]
> > 请问作者项目是什么license？
> 
> 这个不太懂是啥，单纯学习练手用的项目

主要是能不能免费使用？

**Comment by food-billboard** [comment]
> > > 请问作者项目是什么license？
> 
> > 
> 
> > 这个不太懂是啥，单纯学习练手用的项目
> 
> 
> 
> 主要是能不能免费使用？

无所谓吧

**Comment by TonyMistark** [comment]
就喜欢这种随性无所D谓的感觉，话说在后头哈哈哈哈
在[ruanyifeng](http://www.ruanyifeng.com/blog/2023/04/weekly-issue-252.html)这里看到的，来打卡

**Comment by changhuaC** [comment]
大佬能加个VX吗，纯交流

**Comment by food-billboard** [comment]
> 大佬能加个VX吗，纯交流

掘金上私信我可以吗，这里直接那啥不太好吧 https://juejin.cn/user/3632442150778654
